export const mockUsers = {
  alice: {
    friends: ["bob", "charlie", "dave", "eve"],
    groups: ["group1", "group2", "group5"],
    messages: {
      bob: [
        {
          from: "alice",
          to: "bob",
          text: "Hey Bob!",
          timestamp: "2023-08-01T10:00:00Z",
        },
        {
          from: "bob",
          to: "alice",
          text: "Hi Alice!",
          timestamp: "2023-08-01T10:01:00Z",
        },
      ],
      charlie: [
        {
          from: "alice",
          to: "charlie",
          text: "Yo Charlie!",
          timestamp: "2023-08-02T12:00:00Z",
        },
      ],
    },
  },
  bob: {
    friends: ["alice", "grace", "henry"],
    groups: ["group1", "group6"],
    messages: {
      alice: [
        {
          from: "alice",
          to: "bob",
          text: "Hey Bob!",
          timestamp: "2023-08-01T10:00:00Z",
        },
        {
          from: "bob",
          to: "alice",
          text: "Hi Alice!",
          timestamp: "2023-08-01T10:01:00Z",
        },
      ],
    },
  },
  charlie: {
    friends: ["alice", "frank", "iris"],
    groups: ["group2", "group7"],
    messages: {
      alice: [
        {
          from: "alice",
          to: "charlie",
          text: "Yo Charlie!",
          timestamp: "2023-08-02T12:00:00Z",
        },
      ],
    },
  },
  dave: {
    friends: ["alice", "jack", "karen"],
    groups: ["group3", "group8"],
    messages: {},
  },
  eve: {
    friends: ["frank", "alice", "lily"],
    groups: ["group3", "group9"],
    messages: {
      frank: [
        {
          from: "eve",
          to: "frank",
          text: "How's it going, Frank?",
          timestamp: "2023-08-03T09:30:00Z",
        },
      ],
    },
  },
  frank: {
    friends: ["eve", "charlie", "mike"],
    groups: ["group3", "group10"],
    messages: {
      eve: [
        {
          from: "eve",
          to: "frank",
          text: "How's it going, Frank?",
          timestamp: "2023-08-03T09:30:00Z",
        },
      ],
    },
  },
  grace: {
    friends: ["bob", "henry", "nina"],
    groups: ["group4", "group6"],
    messages: {},
  },
  henry: {
    friends: ["bob", "grace", "oscar"],
    groups: ["group4", "group11"],
    messages: {},
  },
  iris: {
    friends: ["charlie", "jack", "paul"],
    groups: ["group5", "group7"],
    messages: {},
  },
  jack: {
    friends: ["dave", "iris", "quinn"],
    groups: ["group6", "group8"],
    messages: {},
  },
  karen: {
    friends: ["dave", "lily", "steve"],
    groups: ["group7", "group9"],
    messages: {},
  },
  lily: {
    friends: ["eve", "karen", "tom"],
    groups: ["group8", "group10"],
    messages: {},
  },
  mike: {
    friends: ["frank", "nina", "victor"],
    groups: ["group9", "group11"],
    messages: {},
  },
  nina: {
    friends: ["grace", "mike", "wendy"],
    groups: ["group10", "group12"],
    messages: {},
  },
  oscar: {
    friends: ["henry", "paul", "xander"],
    groups: ["group11", "group13"],
    messages: {},
  },
  paul: {
    friends: ["iris", "oscar", "yara"],
    groups: ["group12", "group14"],
    messages: {},
  },
  quinn: {
    friends: ["jack", "steve", "zoe"],
    groups: ["group13", "group15"],
    messages: {},
  },
  steve: {
    friends: ["karen", "quinn", "alex"],
    groups: ["group14", "group16"],
    messages: {},
  },
  tom: {
    friends: ["lily", "victor", "bella"],
    groups: ["group15", "group17"],
    messages: {},
  },
  victor: {
    friends: ["mike", "tom", "carlos"],
    groups: ["group16", "group18"],
    messages: {},
  },
  wendy: {
    friends: ["nina", "xander", "diana"],
    groups: ["group17", "group19"],
    messages: {},
  },
  xander: {
    friends: ["oscar", "wendy", "elena"],
    groups: ["group18", "group20"],
    messages: {},
  },
  yara: {
    friends: ["paul", "zoe", "felix"],
    groups: ["group19", "group1"],
    messages: {},
  },
  zoe: {
    friends: ["quinn", "yara", "george"],
    groups: ["group20", "group2"],
    messages: {},
  },
  alex: {
    friends: ["steve", "bella", "hannah"],
    groups: ["group1", "group3"],
    messages: {},
  },
  bella: {
    friends: ["tom", "alex", "ivan"],
    groups: ["group2", "group4"],
    messages: {},
  },
  carlos: {
    friends: ["victor", "diana", "james"],
    groups: ["group3", "group5"],
    messages: {},
  },
  diana: {
    friends: ["wendy", "carlos", "kate"],
    groups: ["group4", "group6"],
    messages: {},
  },
  elena: {
    friends: ["xander", "felix", "liam"],
    groups: ["group5", "group7"],
    messages: {},
  },
  felix: {
    friends: ["yara", "elena", "maya"],
    groups: ["group6", "group8"],
    messages: {},
  },
  george: {
    friends: ["zoe", "hannah", "noah"],
    groups: ["group7", "group9"],
    messages: {},
  },
  hannah: {
    friends: ["alex", "george", "olivia"],
    groups: ["group8", "group10"],
    messages: {},
  },
  ivan: {
    friends: ["bella", "james", "petra"],
    groups: ["group9", "group11"],
    messages: {},
  },
  james: {
    friends: ["carlos", "ivan", "ruby"],
    groups: ["group10", "group12"],
    messages: {},
  },
  kate: {
    friends: ["diana", "liam", "sam"],
    groups: ["group11", "group13"],
    messages: {},
  },
  liam: {
    friends: ["elena", "kate", "tina"],
    groups: ["group12", "group14"],
    messages: {},
  },
  maya: {
    friends: ["felix", "noah", "uma"],
    groups: ["group13", "group15"],
    messages: {},
  },
  noah: {
    friends: ["george", "maya", "vera"],
    groups: ["group14", "group16"],
    messages: {},
  },
  olivia: {
    friends: ["hannah", "petra", "will"],
    groups: ["group15", "group17"],
    messages: {},
  },
  petra: {
    friends: ["ivan", "olivia", "xavier"],
    groups: ["group16", "group18"],
    messages: {},
  },
  ruby: {
    friends: ["james", "sam", "yasmin"],
    groups: ["group17", "group19"],
    messages: {},
  },
  sam: {
    friends: ["kate", "ruby", "zara"],
    groups: ["group18", "group20"],
    messages: {},
  },
  tina: {
    friends: ["liam", "uma", "aaron"],
    groups: ["group19", "group1"],
    messages: {},
  },
  uma: {
    friends: ["maya", "tina", "ben"],
    groups: ["group20", "group2"],
    messages: {},
  },
  vera: {
    friends: ["noah", "will", "chloe"],
    groups: ["group1", "group3"],
    messages: {},
  },
  will: {
    friends: ["olivia", "vera", "david"],
    groups: ["group2", "group4"],
    messages: {},
  },
  xavier: {
    friends: ["petra", "yasmin", "emma"],
    groups: ["group3", "group5"],
    messages: {},
  },
  yasmin: {
    friends: ["ruby", "xavier", "finn"],
    groups: ["group4", "group6"],
    messages: {},
  },
  zara: {
    friends: ["sam", "aaron", "gina"],
    groups: ["group5", "group7"],
    messages: {},
  },
  aaron: {
    friends: ["tina", "zara", "hugo"],
    groups: ["group6", "group8"],
    messages: {},
  },
  ben: {
    friends: ["uma", "chloe", "iris2"],
    groups: ["group7", "group9"],
    messages: {},
  },
  chloe: {
    friends: ["vera", "ben", "jake"],
    groups: ["group8", "group10"],
    messages: {},
  },
  david: {
    friends: ["will", "emma", "luna"],
    groups: ["group9", "group11"],
    messages: {},
  },
  emma: {
    friends: ["xavier", "david", "max"],
    groups: ["group10", "group12"],
    messages: {},
  },
  finn: {
    friends: ["yasmin", "gina", "nora"],
    groups: ["group11", "group13"],
    messages: {},
  },
  gina: {
    friends: ["zara", "finn", "owen"],
    groups: ["group12", "group14"],
    messages: {},
  },
  hugo: {
    friends: ["aaron", "iris2", "piper"],
    groups: ["group13", "group15"],
    messages: {},
  },
  iris2: {
    friends: ["ben", "hugo", "quinn2"],
    groups: ["group14", "group16"],
    messages: {},
  },
  jake: {
    friends: ["chloe", "luna", "riley"],
    groups: ["group15", "group17"],
    messages: {},
  },
  luna: {
    friends: ["david", "jake", "simon"],
    groups: ["group16", "group18"],
    messages: {},
  },
  max: {
    friends: ["emma", "nora", "taylor"],
    groups: ["group17", "group19"],
    messages: {},
  },
  nora: {
    friends: ["finn", "max", "ulysses"],
    groups: ["group18", "group20"],
    messages: {},
  },
  owen: {
    friends: ["gina", "piper", "violet"],
    groups: ["group19", "group1"],
    messages: {},
  },
  piper: {
    friends: ["hugo", "owen", "wyatt"],
    groups: ["group20", "group2"],
    messages: {},
  },
  quinn2: {
    friends: ["iris2", "riley", "ximena"],
    groups: ["group1", "group3"],
    messages: {},
  },
  riley: {
    friends: ["jake", "quinn2", "yuki"],
    groups: ["group2", "group4"],
    messages: {},
  },
  simon: {
    friends: ["luna", "taylor", "zelda"],
    groups: ["group3", "group5"],
    messages: {},
  },
  taylor: {
    friends: ["max", "simon", "adam"],
    groups: ["group4", "group6"],
    messages: {},
  },
  ulysses: {
    friends: ["nora", "violet", "blair"],
    groups: ["group5", "group7"],
    messages: {},
  },
  violet: {
    friends: ["owen", "ulysses", "chase"],
    groups: ["group6", "group8"],
    messages: {},
  },
  wyatt: {
    friends: ["piper", "ximena", "delia"],
    groups: ["group7", "group9"],
    messages: {},
  },
  ximena: {
    friends: ["quinn2", "wyatt", "ethan"],
    groups: ["group8", "group10"],
    messages: {},
  },
  yuki: {
    friends: ["riley", "zelda", "faith"],
    groups: ["group9", "group11"],
    messages: {},
  },
  zelda: {
    friends: ["simon", "yuki", "gavin"],
    groups: ["group10", "group12"],
    messages: {},
  },
  adam: {
    friends: ["taylor", "blair", "hope"],
    groups: ["group11", "group13"],
    messages: {},
  },
  blair: {
    friends: ["ulysses", "adam", "isaac"],
    groups: ["group12", "group14"],
    messages: {},
  },
  chase: {
    friends: ["violet", "delia", "jade"],
    groups: ["group13", "group15"],
    messages: {},
  },
  delia: {
    friends: ["wyatt", "chase", "kyle"],
    groups: ["group14", "group16"],
    messages: {},
  },
  ethan: {
    friends: ["ximena", "faith", "leah"],
    groups: ["group15", "group17"],
    messages: {},
  },
  faith: {
    friends: ["yuki", "ethan", "mason"],
    groups: ["group16", "group18"],
    messages: {},
  },
  gavin: {
    friends: ["zelda", "hope", "nancy"],
    groups: ["group17", "group19"],
    messages: {},
  },
  hope: {
    friends: ["adam", "gavin", "orion"],
    groups: ["group18", "group20"],
    messages: {},
  },
  isaac: {
    friends: ["blair", "jade", "penny"],
    groups: ["group19", "group1"],
    messages: {},
  },
  jade: {
    friends: ["chase", "isaac", "river"],
    groups: ["group20", "group2"],
    messages: {},
  },
  kyle: {
    friends: ["delia", "leah", "sage"],
    groups: ["group1", "group3"],
    messages: {},
  },
  leah: {
    friends: ["ethan", "kyle", "theo"],
    groups: ["group2", "group4"],
    messages: {},
  },
  mason: {
    friends: ["faith", "nancy", "unity"],
    groups: ["group3", "group5"],
    messages: {},
  },
  nancy: {
    friends: ["gavin", "mason", "vance"],
    groups: ["group4", "group6"],
    messages: {},
  },
  orion: {
    friends: ["hope", "penny", "wade"],
    groups: ["group5", "group7"],
    messages: {},
  },
  penny: {
    friends: ["isaac", "orion", "xara"],
    groups: ["group6", "group8"],
    messages: {},
  },
  river: {
    friends: ["jade", "sage", "yale"],
    groups: ["group7", "group9"],
    messages: {},
  },
  sage: {
    friends: ["kyle", "river", "zain"],
    groups: ["group8", "group10"],
    messages: {},
  },
  theo: {
    friends: ["leah", "unity", "aria"],
    groups: ["group9", "group11"],
    messages: {},
  },
  unity: {
    friends: ["mason", "theo", "blake"],
    groups: ["group10", "group12"],
    messages: {},
  },
  vance: {
    friends: ["nancy", "wade", "claire"],
    groups: ["group11", "group13"],
    messages: {},
  },
  wade: {
    friends: ["orion", "vance", "drew"],
    groups: ["group12", "group14"],
    messages: {},
  },
  xara: {
    friends: ["penny", "yale", "eric"],
    groups: ["group13", "group15"],
    messages: {},
  },
  yale: {
    friends: ["river", "xara", "faye"],
    groups: ["group14", "group16"],
    messages: {},
  },
  zain: {
    friends: ["sage", "aria", "gray"],
    groups: ["group15", "group17"],
    messages: {},
  },
  aria: {
    friends: ["theo", "zain", "heath"],
    groups: ["group16", "group18"],
    messages: {},
  },
  blake: {
    friends: ["unity", "claire", "iris3"],
    groups: ["group17", "group19"],
    messages: {},
  },
  claire: {
    friends: ["vance", "blake", "jude"],
    groups: ["group18", "group20"],
    messages: {},
  },
  drew: {
    friends: ["wade", "eric", "kira"],
    groups: ["group19", "group1"],
    messages: {},
  },
  eric: {
    friends: ["xara", "drew", "lana"],
    groups: ["group20", "group2"],
    messages: {},
  },
  faye: {
    friends: ["yale", "gray", "marco"],
    groups: ["group1", "group3"],
    messages: {},
  },
  gray: {
    friends: ["zain", "faye", "nova"],
    groups: ["group2", "group4"],
    messages: {},
  },
  heath: {
    friends: ["aria", "iris3", "ocean"],
    groups: ["group3", "group5"],
    messages: {},
  },
  iris3: {
    friends: ["blake", "heath", "phoenix"],
    groups: ["group4", "group6"],
    messages: {},
  },
  jude: {
    friends: ["claire", "kira", "quill"],
    groups: ["group5", "group7"],
    messages: {},
  },
  kira: {
    friends: ["drew", "jude", "roman"],
    groups: ["group6", "group8"],
    messages: {},
  },
  lana: {
    friends: ["eric", "marco", "storm"],
    groups: ["group7", "group9"],
    messages: {},
  },
  marco: {
    friends: ["faye", "lana", "titan"],
    groups: ["group8", "group10"],
    messages: {},
  },
  nova: {
    friends: ["gray", "ocean", "urban"],
    groups: ["group9", "group11"],
    messages: {},
  },
  ocean: {
    friends: ["heath", "nova", "vega"],
    groups: ["group10", "group12"],
    messages: {},
  },
  phoenix: {
    friends: ["iris3", "quill", "winter"],
    groups: ["group11", "group13"],
    messages: {},
  },
  quill: {
    friends: ["jude", "phoenix", "xerxes"],
    groups: ["group12", "group14"],
    messages: {},
  },
  roman: {
    friends: ["kira", "storm", "yael"],
    groups: ["group13", "group15"],
    messages: {},
  },
  storm: {
    friends: ["lana", "roman", "zephyr"],
    groups: ["group14", "group16"],
    messages: {},
  },
  titan: {
    friends: ["marco", "urban", "aurora"],
    groups: ["group15", "group17"],
    messages: {},
  },
  urban: {
    friends: ["nova", "titan", "blaze"],
    groups: ["group16", "group18"],
    messages: {},
  },
  vega: {
    friends: ["ocean", "winter", "cosmos"],
    groups: ["group17", "group19"],
    messages: {},
  },
  winter: {
    friends: ["phoenix", "vega", "dusk"],
    groups: ["group18", "group20"],
    messages: {},
  },
  xerxes: {
    friends: ["quill", "yael", "echo"],
    groups: ["group19", "group1"],
    messages: {},
  },
  yael: {
    friends: ["roman", "xerxes", "flux"],
    groups: ["group20", "group2"],
    messages: {},
  },
  zephyr: {
    friends: ["storm", "aurora", "grove"],
    groups: ["group1", "group3"],
    messages: {},
  },
  aurora: {
    friends: ["titan", "zephyr", "haven"],
    groups: ["group2", "group4"],
    messages: {},
  },
  blaze: {
    friends: ["urban", "cosmos", "ivory"],
    groups: ["group3", "group5"],
    messages: {},
  },
  cosmos: {
    friends: ["vega", "blaze", "jazz"],
    groups: ["group4", "group6"],
    messages: {},
  },
  dusk: {
    friends: ["winter", "echo", "knight"],
    groups: ["group5", "group7"],
    messages: {},
  },
  echo: {
    friends: ["xerxes", "dusk", "lynx"],
    groups: ["group6", "group8"],
    messages: {},
  },
  flux: {
    friends: ["yael", "grove", "mist"],
    groups: ["group7", "group9"],
    messages: {},
  },
  grove: {
    friends: ["zephyr", "flux", "neon"],
    groups: ["group8", "group10"],
    messages: {},
  },
  haven: {
    friends: ["aurora", "ivory", "onyx"],
    groups: ["group9", "group11"],
    messages: {},
  },
  ivory: {
    friends: ["blaze", "haven", "prism"],
    groups: ["group10", "group12"],
    messages: {},
  },
  jazz: {
    friends: ["cosmos", "knight", "quest"],
    groups: ["group11", "group13"],
    messages: {},
  },
  knight: {
    friends: ["dusk", "jazz", "raven"],
    groups: ["group12", "group14"],
    messages: {},
  },
  lynx: {
    friends: ["echo", "mist", "shade"],
    groups: ["group13", "group15"],
    messages: {},
  },
  mist: {
    friends: ["flux", "lynx", "torch"],
    groups: ["group14", "group16"],
    messages: {},
  },
  neon: {
    friends: ["grove", "onyx", "ultra"],
    groups: ["group15", "group17"],
    messages: {},
  },
  onyx: {
    friends: ["haven", "neon", "valor"],
    groups: ["group16", "group18"],
    messages: {},
  },
  prism: {
    friends: ["ivory", "quest", "wild"],
    groups: ["group17", "group19"],
    messages: {},
  },
  quest: {
    friends: ["jazz", "prism", "xray"],
    groups: ["group18", "group20"],
    messages: {},
  },
  raven: {
    friends: ["knight", "shade", "youth"],
    groups: ["group19", "group1"],
    messages: {},
  },
  shade: {
    friends: ["lynx", "raven", "zen"],
    groups: ["group20", "group2"],
    messages: {},
  },
  torch: {
    friends: ["mist", "ultra", "apex"],
    groups: ["group1", "group3"],
    messages: {},
  },
  ultra: {
    friends: ["neon", "torch", "brave"],
    groups: ["group2", "group4"],
    messages: {},
  },
  valor: {
    friends: ["onyx", "wild", "cyber"],
    groups: ["group3", "group5"],
    messages: {},
  },
  wild: {
    friends: ["prism", "valor", "drift"],
    groups: ["group4", "group6"],
    messages: {},
  },
  xray: {
    friends: ["quest", "youth", "edge"],
    groups: ["group5", "group7"],
    messages: {},
  },
  youth: {
    friends: ["raven", "xray", "frost"],
    groups: ["group6", "group8"],
    messages: {},
  },
  zen: {
    friends: ["shade", "apex", "ghost"],
    groups: ["group7", "group9"],
    messages: {},
  },
  apex: {
    friends: ["torch", "zen", "halo"],
    groups: ["group8", "group10"],
    messages: {},
  },
  brave: {
    friends: ["ultra", "cyber", "ion"],
    groups: ["group9", "group11"],
    messages: {},
  },
  cyber: {
    friends: ["valor", "brave", "jet"],
    groups: ["group10", "group12"],
    messages: {},
  },
  drift: {
    friends: ["wild", "edge", "kick"],
    groups: ["group11", "group13"],
    messages: {},
  },
  edge: {
    friends: ["xray", "drift", "lunar"],
    groups: ["group12", "group14"],
    messages: {},
  },
  frost: {
    friends: ["youth", "ghost", "metro"],
    groups: ["group13", "group15"],
    messages: {},
  },
  ghost: {
    friends: ["zen", "frost", "nexus"],
    groups: ["group14", "group16"],
    messages: {},
  },
  halo: {
    friends: ["apex", "ion", "orbit"],
    groups: ["group15", "group17"],
    messages: {},
  },
  ion: {
    friends: ["brave", "halo", "pulse"],
    groups: ["group16", "group18"],
    messages: {},
  },
  jet: {
    friends: ["cyber", "kick", "radar"],
    groups: ["group17", "group19"],
    messages: {},
  },
  kick: {
    friends: ["drift", "jet", "spark"],
    groups: ["group18", "group20"],
    messages: {},
  },
  lunar: {
    friends: ["edge", "metro", "tempo"],
    groups: ["group19", "group1"],
    messages: {},
  },
  metro: {
    friends: ["frost", "lunar", "unity2"],
    groups: ["group20", "group2"],
    messages: {},
  },
  nexus: {
    friends: ["ghost", "orbit", "vortex"],
    groups: ["group1", "group3"],
    messages: {},
  },
  orbit: {
    friends: ["halo", "nexus", "wave"],
    groups: ["group2", "group4"],
    messages: {},
  },
  pulse: {
    friends: ["ion", "radar", "xtreme"],
    groups: ["group3", "group5"],
    messages: {},
  },
  radar: {
    friends: ["jet", "pulse", "yield"],
    groups: ["group4", "group6"],
    messages: {},
  },
  spark: {
    friends: ["kick", "tempo", "zenith"],
    groups: ["group5", "group7"],
    messages: {},
  },
  tempo: {
    friends: ["lunar", "spark", "alpha"],
    groups: ["group6", "group8"],
    messages: {},
  },
  unity2: {
    friends: ["metro", "vortex", "beta"],
    groups: ["group7", "group9"],
    messages: {},
  },
  vortex: {
    friends: ["nexus", "unity2", "gamma"],
    groups: ["group8", "group10"],
    messages: {},
  },
  wave: {
    friends: ["orbit", "xtreme", "delta"],
    groups: ["group9", "group11"],
    messages: {},
  },
  xtreme: {
    friends: ["pulse", "wave", "sigma"],
    groups: ["group10", "group12"],
    messages: {},
  },
  yield: {
    friends: ["radar", "zenith", "omega"],
    groups: ["group11", "group13"],
    messages: {},
  },
  zenith: {
    friends: ["spark", "yield", "theta"],
    groups: ["group12", "group14"],
    messages: {},
  },
  alpha: {
    friends: ["tempo", "beta", "lambda"],
    groups: ["group13", "group15"],
    messages: {},
  },
  beta: {
    friends: ["unity2", "alpha", "kappa"],
    groups: ["group14", "group16"],
    messages: {},
  },
  gamma: {
    friends: ["vortex", "delta", "phi"],
    groups: ["group15", "group17"],
    messages: {},
  },
  delta: {
    friends: ["wave", "gamma", "psi"],
    groups: ["group16", "group18"],
    messages: {},
  },
  sigma: {
    friends: ["xtreme", "omega", "chi"],
    groups: ["group17", "group19"],
    messages: {},
  },
  omega: {
    friends: ["yield", "sigma", "rho"],
    groups: ["group18", "group20"],
    messages: {},
  },
  theta: {
    friends: ["zenith", "lambda", "tau"],
    groups: ["group19", "group1"],
    messages: {},
  },
  lambda: {
    friends: ["alpha", "theta", "epsilon"],
    groups: ["group20", "group2"],
    messages: {},
  },
  kappa: {
    friends: ["beta", "phi", "zeta"],
    groups: ["group1", "group3"],
    messages: {},
  },
  phi: {
    friends: ["gamma", "kappa", "eta"],
    groups: ["group2", "group4"],
    messages: {},
  },
  psi: {
    friends: ["delta", "chi", "mu"],
    groups: ["group3", "group5"],
    messages: {},
  },
  chi: {
    friends: ["sigma", "psi", "nu"],
    groups: ["group4", "group6"],
    messages: {},
  },
  rho: {
    friends: ["omega", "tau", "xi"],
    groups: ["group5", "group7"],
    messages: {},
  },
  tau: {
    friends: ["theta", "rho", "pi"],
    groups: ["group6", "group8"],
    messages: {},
  },
  epsilon: {
    friends: ["lambda", "zeta", "upsilon"],
    groups: ["group7", "group9"],
    messages: {},
  },
  zeta: {
    friends: ["kappa", "epsilon", "iota"],
    groups: ["group8", "group10"],
    messages: {},
  },
  eta: {
    friends: ["phi", "mu", "beta2"],
    groups: ["group9", "group11"],
    messages: {},
  },
  mu: {
    friends: ["psi", "eta", "gamma2"],
    groups: ["group10", "group12"],
    messages: {},
  },
  nu: {
    friends: ["chi", "xi", "delta2"],
    groups: ["group11", "group13"],
    messages: {},
  },
  xi: {
    friends: ["rho", "nu", "sigma2"],
    groups: ["group12", "group14"],
    messages: {},
  },
  pi: {
    friends: ["tau", "upsilon", "omega2"],
    groups: ["group13", "group15"],
    messages: {},
  },
  upsilon: {
    friends: ["epsilon", "pi", "theta2"],
    groups: ["group14", "group16"],
    messages: {},
  },
  iota: {
    friends: ["zeta", "beta2", "lambda2"],
    groups: ["group15", "group17"],
    messages: {},
  },
  beta2: {
    friends: ["eta", "iota", "kappa2"],
    groups: ["group16", "group18"],
    messages: {},
  },
  gamma2: {
    friends: ["mu", "delta2", "phi2"],
    groups: ["group17", "group19"],
    messages: {},
  },
  delta2: {
    friends: ["nu", "gamma2", "psi2"],
    groups: ["group18", "group20"],
    messages: {},
  },
  sigma2: {
    friends: ["xi", "omega2", "chi2"],
    groups: ["group19", "group1"],
    messages: {},
  },
  omega2: {
    friends: ["pi", "sigma2", "rho2"],
    groups: ["group20", "group2"],
    messages: {},
  },
  theta2: {
    friends: ["upsilon", "lambda2", "tau2"],
    groups: ["group1", "group3"],
    messages: {},
  },
  lambda2: {
    friends: ["iota", "theta2", "epsilon2"],
    groups: ["group2", "group4"],
    messages: {},
  },
  kappa2: {
    friends: ["beta2", "phi2", "zeta2"],
    groups: ["group3", "group5"],
    messages: {},
  },
  phi2: {
    friends: ["gamma2", "kappa2", "eta2"],
    groups: ["group4", "group6"],
    messages: {},
  },
  psi2: {
    friends: ["delta2", "chi2", "mu2"],
    groups: ["group5", "group7"],
    messages: {},
  },
  chi2: {
    friends: ["sigma2", "psi2", "nu2"],
    groups: ["group6", "group8"],
    messages: {},
  },
  rho2: {
    friends: ["omega2", "tau2", "xi2"],
    groups: ["group7", "group9"],
    messages: {},
  },
  tau2: {
    friends: ["theta2", "rho2", "pi2"],
    groups: ["group8", "group10"],
    messages: {},
  },
  epsilon2: {
    friends: ["lambda2", "zeta2", "upsilon2"],
    groups: ["group9", "group11"],
    messages: {},
  },
  zeta2: {
    friends: ["kappa2", "epsilon2", "iota2"],
    groups: ["group10", "group12"],
    messages: {},
  },
  eta2: {
    friends: ["phi2", "mu2", "alice"],
    groups: ["group11", "group13"],
    messages: {},
  },
  mu2: {
    friends: ["psi2", "eta2", "bob"],
    groups: ["group12", "group14"],
    messages: {},
  },
  nu2: {
    friends: ["chi2", "xi2", "charlie"],
    groups: ["group13", "group15"],
    messages: {},
  },
  xi2: {
    friends: ["rho2", "nu2", "dave"],
    groups: ["group14", "group16"],
    messages: {},
  },
  pi2: {
    friends: ["tau2", "upsilon2", "eve"],
    groups: ["group15", "group17"],
    messages: {},
  },
  upsilon2: {
    friends: ["epsilon2", "pi2", "frank"],
    groups: ["group16", "group18"],
    messages: {},
  },
  iota2: {
    friends: ["zeta2", "alice", "grace"],
    groups: ["group17", "group19"],
    messages: {},
  },
};

export const mockGroups = {
  group1: {
    groupId: "group1",
    groupName: "Main Hub",
    createdBy: "alice",
    members: [
      "alice",
      "bob",
      "charlie",
      "dave",
      "eve",
      "frank",
      "grace",
      "henry",
      "iris",
      "jack",
    ],
    messages: [
      {
        from: "alice",
        text: "Welcome to the main hub!",
        timestamp: "2023-08-04T10:00:00Z",
      },
      {
        from: "bob",
        text: "Great to be here with everyone!",
        timestamp: "2023-08-04T10:05:00Z",
      },
    ],
  },
  group2: {
    groupId: "group2",
    groupName: "Development Team",
    createdBy: "alice",
    members: [
      "alice",
      "charlie",
      "karen",
      "lily",
      "mike",
      "nina",
      "oscar",
      "paul",
    ],
    messages: [
      {
        from: "charlie",
        text: "Ready for today's sprint?",
        timestamp: "2023-08-05T12:00:00Z",
      },
      {
        from: "alice",
        text: "Let's build something amazing! 🚀",
        timestamp: "2023-08-05T12:03:00Z",
      },
    ],
  },
  group3: {
    groupId: "group3",
    groupName: "Creative Corner",
    createdBy: "eve",
    members: [
      "eve",
      "frank",
      "quinn",
      "steve",
      "tom",
      "victor",
      "wendy",
      "xander",
    ],
    messages: [
      {
        from: "eve",
        text: "Share your creative ideas here!",
        timestamp: "2023-08-06T09:00:00Z",
      },
      {
        from: "frank",
        text: "Love the creative energy! 🎨",
        timestamp: "2023-08-06T09:05:00Z",
      },
    ],
  },
  group4: {
    groupId: "group4",
    groupName: "Tech Innovators",
    createdBy: "grace",
    members: [
      "grace",
      "henry",
      "yara",
      "zoe",
      "alex",
      "bella",
      "carlos",
      "diana",
    ],
    messages: [],
  },
  group5: {
    groupId: "group5",
    groupName: "Project Alpha",
    createdBy: "iris",
    members: [
      "iris",
      "alice",
      "elena",
      "felix",
      "george",
      "hannah",
      "ivan",
      "james",
    ],
    messages: [],
  },
  group6: {
    groupId: "group6",
    groupName: "Beta Testing",
    createdBy: "jack",
    members: ["jack", "bob", "grace", "kate", "liam", "maya", "noah", "olivia"],
    messages: [],
  },
  group7: {
    groupId: "group7",
    groupName: "Gamma Squad",
    createdBy: "karen",
    members: [
      "karen",
      "charlie",
      "iris",
      "petra",
      "ruby",
      "sam",
      "tina",
      "uma",
    ],
    messages: [],
  },
  group8: {
    groupId: "group8",
    groupName: "Delta Force",
    createdBy: "lily",
    members: [
      "lily",
      "dave",
      "jack",
      "vera",
      "will",
      "xavier",
      "yasmin",
      "zara",
    ],
    messages: [],
  },
  group9: {
    groupId: "group9",
    groupName: "Epsilon Elite",
    createdBy: "mike",
    members: ["mike", "eve", "karen", "aaron", "ben", "chloe", "david", "emma"],
    messages: [],
  },
  group10: {
    groupId: "group10",
    groupName: "Zeta Zone",
    createdBy: "nina",
    members: ["nina", "frank", "lily", "finn", "gina", "hugo", "iris2", "jake"],
    messages: [],
  },
  group11: {
    groupId: "group11",
    groupName: "Eta Explorers",
    createdBy: "oscar",
    members: ["oscar", "henry", "mike", "luna", "max", "nora", "owen", "piper"],
    messages: [],
  },
  group12: {
    groupId: "group12",
    groupName: "Theta Thinkers",
    createdBy: "paul",
    members: [
      "paul",
      "nina",
      "quinn2",
      "riley",
      "simon",
      "taylor",
      "ulysses",
      "violet",
    ],
    messages: [],
  },
  group13: {
    groupId: "group13",
    groupName: "Iota Innovators",
    createdBy: "quinn",
    members: [
      "quinn",
      "oscar",
      "wyatt",
      "ximena",
      "yuki",
      "zelda",
      "adam",
      "blair",
    ],
    messages: [],
  },
  group14: {
    groupId: "group14",
    groupName: "Kappa Collective",
    createdBy: "steve",
    members: [
      "steve",
      "paul",
      "chase",
      "delia",
      "ethan",
      "faith",
      "gavin",
      "hope",
    ],
    messages: [],
  },
  group15: {
    groupId: "group15",
    groupName: "Lambda Labs",
    createdBy: "tom",
    members: [
      "tom",
      "quinn",
      "isaac",
      "jade",
      "kyle",
      "leah",
      "mason",
      "nancy",
    ],
    messages: [],
  },
  group16: {
    groupId: "group16",
    groupName: "Mu Masters",
    createdBy: "victor",
    members: [
      "victor",
      "steve",
      "orion",
      "penny",
      "river",
      "sage",
      "theo",
      "unity",
    ],
    messages: [],
  },
  group17: {
    groupId: "group17",
    groupName: "Nu Network",
    createdBy: "wendy",
    members: ["wendy", "tom", "vance", "wade", "xara", "yale", "zain", "aria"],
    messages: [],
  },
  group18: {
    groupId: "group18",
    groupName: "Xi Xperts",
    createdBy: "xander",
    members: [
      "xander",
      "victor",
      "blake",
      "claire",
      "drew",
      "eric",
      "faye",
      "gray",
    ],
    messages: [],
  },
  group19: {
    groupId: "group19",
    groupName: "Omicron Ops",
    createdBy: "yara",
    members: [
      "yara",
      "wendy",
      "heath",
      "iris3",
      "jude",
      "kira",
      "lana",
      "marco",
    ],
    messages: [],
  },
  group20: {
    groupId: "group20",
    groupName: "Pi Pioneers",
    createdBy: "zoe",
    members: [
      "zoe",
      "xander",
      "nova",
      "ocean",
      "phoenix",
      "quill",
      "roman",
      "storm",
    ],
    messages: [],
  },
};
